---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: pulp-example-clowd
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: pulp-example-cloud
  spec:
    deployments:
      - name: pulp-api
        progressDeadlineSeconds: 600
        replicas: 1
        revisionHistoryLimit: 10
        selector:
          matchLabels:
            app: pulp-api
            app.kubernetes.io/component: api
            app.kubernetes.io/instance: pulp-api-example-pulp
            app.kubernetes.io/managed-by: pulp-operator
            app.kubernetes.io/name: pulp-api
            app.kubernetes.io/part-of: pulp
            pulp_cr: example-pulp
        strategy:
          rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
          type: RollingUpdate
        template:
          metadata:
            creationTimestamp: null
            labels:
              app: pulp-api
              app.kubernetes.io/component: api
              app.kubernetes.io/instance: pulp-api-example-pulp
              app.kubernetes.io/managed-by: pulp-operator
              app.kubernetes.io/name: pulp-api
              app.kubernetes.io/part-of: pulp
              pulp_cr: example-pulp
          spec:
            affinity: {}
            containers:
            - args:
              - pulp-api
              env:
              - name: PULP_GUNICORN_TIMEOUT
                value: "90"
              - name: PULP_API_WORKERS
                value: "2"
              - name: POSTGRES_SERVICE_HOST
                value: example-pulp-database-svc
              - name: POSTGRES_SERVICE_PORT
                value: "5432"
              image: quay.io/pulp/pulp-minimal:latest
              imagePullPolicy: IfNotPresent
              livenessProbe:
                failureThreshold: 5
                httpGet:
                  path: /pulp/api/v3/status/
                  port: 24817
                  scheme: HTTP
                initialDelaySeconds: 120
                periodSeconds: 20
                successThreshold: 1
                timeoutSeconds: 10
              name: api
              ports:
              - containerPort: 24817
                protocol: TCP
              readinessProbe:
                exec:
                  command:
                  - /usr/bin/readyz.py
                  - /pulp/api/v3/status/
                failureThreshold: 10
                initialDelaySeconds: 60
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 10
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
              - mountPath: /etc/pulp/settings.py
                name: example-pulp-server
                readOnly: true
                subPath: settings.py
              - mountPath: /etc/pulp/pulp-admin-password
                name: example-pulp-admin-password
                readOnly: true
                subPath: admin-password
              - mountPath: /etc/pulp/keys/database_fields.symmetric.key
                name: example-pulp-db-fields-encryption
                readOnly: true
                subPath: database_fields.symmetric.key
              - mountPath: /etc/pulp/keys/container_auth_private_key.pem
                name: example-pulp-container-auth-certs
                readOnly: true
                subPath: container_auth_private_key.pem
              - mountPath: /etc/pulp/keys/container_auth_public_key.pem
                name: example-pulp-container-auth-certs
                readOnly: true
                subPath: container_auth_pulblic_key.pem
            dnsPolicy: ClusterFirst
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            serviceAccount: example-pulp
            serviceAccountName: example-pulp
            terminationGracePeriodSeconds: 30
            volumes:
            - name: example-pulp-server
              secret:
                defaultMode: 420
                items:
                - key: settings.py
                  path: settings.py
                secretName: example-pulp-server
            - name: example-pulp-admin-password
              secret:
                defaultMode: 420
                items:
                - key: password
                  path: admin-password
                secretName: example-pulp-admin-password
            - name: example-pulp-db-fields-encryption
              secret:
                defaultMode: 420
                items:
                - key: database_fields.symmetric.key
                  path: database_fields.symmetric.key
                secretName: example-pulp-db-fields-encryption
            - name: example-pulp-container-auth-certs
              secret:
                defaultMode: 420
                items:
                - key: container_auth_public_key.pem
                  path: container_auth_public_key.pem
                - key: container_auth_private_key.pem
                  path: container_auth_private_key.pem
                secretName: example-pulp-container-auth
